### ISSUE TITLE
Many debug errors appear at game start

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [Noctifer-de-Mortem/nocts_cata_mod#10]
@Noctifer-de-Mortem When a character is created in a world using Cataclysm++ several errors appear:

2x "JsonObject contains legacy node 'gun_bionic'.  Consider replacing it with 'BIONIC_GUN' in 'flags' node."

"JsonObject contains legacy node 'toggled'.  Consider replacing it with 'BIONIC_TOGGLED' in 'flags' node."

"JsonObject contains legacy node 'weapon_bionic'.  Consider replacing it with 'BIONIC_WEAPON' in 'flags' node."

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(38) can't be installed to 0,0

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(53) can't be installed to 0,0

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(105) can't be installed to 0,0

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(112) can't be installed to 0,0

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(125) can't be installed to 0,0

"init_vehicles: 'Survivor's RV' part 'ups_rifle_t'(132) can't be installed to 0,0

etc.

"warnings for type lmg_handle: gunmod must have both sight_dispersion and aim_speed set or neither of them set

"warnings for type surv_laser_sight: gunmod must have both sight_disersion and aim_speed set or neither of them set"

"Mutation category mutation_bio_weapon has threshold mutation THRESH_BIO-WEAPON, which does not exist"

**Comment by chaosvolt** [comment]
Woah. Um. I've seen all those errors before.

You sure you'e testing with with the absolute latest version of the master branch?

**Comment by BorkBorkGoesTheCode** [comment]
Same here
