### ISSUE TITLE
Using codepage numbers in overmap terrains adds a debug message to debug.txt

### ISSUE THREAD

**Issue by Throwaway-name** [Noctifer-de-Mortem/nocts_cata_mod#102]
> 
> sym is defined as number instead of string for overmap_terrain: robot_dispatch_first (robot dispatch center)
> 12:23:00.834 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: robot_dispatch_second (robot dispatch center)
> 12:23:00.900 ERROR : couldn't parse color: c_light_brown
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: biow_field (field)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: bio_field (parking lot)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Bio_Weapon_Lab (Bio-Weapon Lab)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: makeshift_command_center (Makeshift Command Center)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: b2_field (parking lot)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Survivor_Holdout (Survivor Holdout)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab (Unknown Lab)
> 12:23:00.907 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Bunker (Unknown Bunker)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Survivor_Holdout_1 (Survivor Holdout)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: surv_camp (forest)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: surv_emcampz (Survivor Encampment)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: surv_emcampb (Survivor Encampment)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: surv_emcampn (Survivor Encampment)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: surv_emcampnp (Survivor Encampment)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Bio_Weapon_Lab_1 (parking lot)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Bio_Weapon_Lab_2 (Bio-Weapon Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Bio_Weapon_Lab_b (Bio-Weapon Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_1 (parking lot)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_2 (parking lot)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_3 (dormitories)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_4 (Unknown Bunker)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_b1 (Unknown Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_b2 (Unknown Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_b3 (Unknown Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: Unknown_Lab_b4 (Unknown Lab)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: makeshift_command_center_1 (parking lot)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: makeshift_command_center_2 (Makeshift Command Center)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: makeshift_command_center_b (Makeshift Command Center)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: b_field (field)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: house_fight (Sketchy Cabin)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: forest_slaghter (forest)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: plain_slaughter1 (field)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: plain_slaughter2 (field)
> 12:23:00.908 ERROR MAP_GEN : sym is defined as number instead of string for overmap_terrain: new_fungal_territory (fungal field)

**Comment by chaosvolt** [comment]
*oof*

Time to fix that for Noct too, it seems....

I noticed this in debug logs before, and been putting it off for Dorf Life because it will rush my setting aside a 0.D stable release when I had some things unfinished, but I should likely just branch it and fix that for all the mods now.

This is on top of needing to do time fixes for every single mod I'm a maintainer of...

**Comment by Throwaway-name** [comment]
I've teleported to one of the affected maps and nothing seems out of place, so I've replaced the false title.

**Comment by chaosvolt** [comment]
If I recall it's just in the debug log, not an actual load error, right? That's why I've been slacking about fixing them...
