### ISSUE TITLE
attempting to talk to the NPC in the bio lab start crashes the game

### ISSUE THREAD

**Issue by kingofzdom** [Noctifer-de-Mortem/nocts_cata_mod#106]

**Comment by chaosvolt** [comment]
Finally got around to testing this, latest build and version of the mod. You're right, but I'm seeing the same weird m_construct shit that was happening basically all the time back when the builds were corrupting data. Not sure of the cause...

**Comment by chaosvolt** [comment]
Running into same issue with guard at the command center, possibly all Cata++ NPCs. About to go test with Arcana to see if it's not just some "all NPCs in mods are shitting their brains out" issue.
