### ISSUE TITLE
Overhaul Project: Survivor Combatives

### ISSUE THREAD

**Issue by chaosvolt** [Noctifer-de-Mortem/nocts_cata_mod#129]
Having been aware of the impressive work by @Hymore246 regarding overhauling vanilla martial arts, I've been meaning to organize and summarize how Noct's current iteration of Survivor Combatives works, and try to figure out how best to improve it. And...actually looking it over for the first time in a while, wooo boy this is going to be a doozy...

`You learned how to handle yourself in the cataclysm.  You have become good at using proper, improvised and hand made weaponry, including your fists.  Not flashy but it keeps you alive.`

Name | Level Available | Other Requirements | Type | Effect
------------ | ------------- | ------------- | ------------- | -------------
Weapon Focus | Melee 6 | N/A | Melee Static Buff | +3 bonus dodges, +3 bonus blocks
Unarmed Focus | Unarmed 6 | N/A | Unarmed Static Buff | +3 bonus dodges, +3 bonus blocks
Combat Roll | Melee 8 | N/A | Static Buff | Throw immunity
Ultimate Weapon Focus | Melee 10 | N/A | Melee Static Buff | +99 bonus dodge, +99 bonus blocks (!?)
Ultimate Unarmed Focus | Unarmed 10 | N/A | Unarmed Static Buff | +99 bonus dodge, +99 bonus blocks (!?)
Quiet Unarmed Combat | Unarmed 10 | N/A | Unarmed Static Buff | Silent attacks
Quiet Weapon Combat | Melee 10 | N/A | Melee Static Buff | Silent attacks
Combat Momentum | Melee 8 | N/A | OnAttack Buff | +1.5 bash/cut/stab damage, +1.25 damage. Last 5 turns, stacks 10 times (!!!)
Deadly Momentum | Melee 10 | N/A | OnKill Buff | +2 bash/cut/stab damage, +1.5 damage. Last 5 turns, stacks 10 times (!!!)
Grab Break | Melee 4 | N/A | Melee Tech | Defensive grab break
Grab Break | Unarmed 4 | N/A | Unarmed Tech | Defensive grab break
Counter | Melee 4 | N/A | Melee Tech | Block counter, 0% movecost, crits allowed (?)
Counter | Unarmed 4 | N/A | Unarmed Tech | Block counter, 0% movecost, crits allowed (?)
Feint | Melee 3 | N/A | Melee Tech | Defensive miss recovery (?)
Feint | Unarmed 3 | N/A | Unarmed Tech | Defensive miss recovery, +1.5 accuracy (!?)
Disarm | Melee 5 | N/A | Melee Tech | Disarms, crits allowed
Disarm | Unarmed 5 | N/A | Unarmed Tech | Disarms, crits allowed
Power Hit | Unarmed 4 | N/A | Unarmed Crit Tech | Knockback 1, stuns for 1 turn
Power Strike | Melee 4 | N/A | Melee Crit Tech | Knockback 1, stuns for 1 turn
Trip | Unarmed 3 | N/A | Unarmed Tech | Knockdown for 1 turn
Trip | Melee 3 | N/A | Melee Tech | Knockdown for 1 turn
Quick Punch | Unarmed 2 | N/A | Unarmed Tech | 25% movecost, 50% bash/cut/stab damage
Quick Strike | Melee 2 | N/A | Melee Tech | 50% movecost, 75% bash/cut/stab damage
Precise Strike | Unarmed 6 | N/A | Unarmed Crit Tech | Stuns for 2 turns
Precise Strike | Melee 6 | N/A | Melee Crit Tech | Stuns for 2 turns
Surprise Attack | Unarmed 6 | N/A | Unarmed Crit Tech | 200% bash/cut/stab damage, stuns for 2 turns
Surprise Attack | Melee 6 | N/A | Melee Crit Tech | 200% bash/cut/stab damage, stuns for 2 turns

Weapons: none (dunno if this still works for an armed martial art...)

Things that stand out:
* +99 bonus blocks and dodges is broken as all hell, one way or another. Either it makes you invulnerable, or it's a recipe for stunlocking yourself, and I don't have the faintest clue which way it'll prefer to go.
* Flat bonuses generally don't like having decimal increases, so the accuracy and damage buffs won't quite work together very well.
* Lots of redundant techniques, but this is understandable given it has unarmed versions of everything it does. Even then, some techs and buffs could potentially be merged to some extent.
* Progression is rather wonky for a style that seems to be intended as an advanced, post-cataclysm martial arts system. Techniques are all primarily at skill level, while buffs are primarily at high skill level. This could be make to work, but it is still a peculiar system.
* Arm and leg blocks are set to never be unlocked due to being at 99, which refers to what level of unarmed you become able to block with them. This is potentially odd for an all-rounder style, especially one that doles out a lot of bonus blocks.
* Quick Punch/Strike is pretty potent for a rapid-strike tech, vastly out-performing all other sources of rapid attack at a very low level.
* Surprise Attack has no real way to actually be a surprise attack given it comes out purely at random, and double damage is pretty beefy for something that already happens on critical hits.
* Unarmed version of Feint gets an accuracy bonus that I'm 99% certain won't actually help any, given you've already missed when it triggers.
* Feint probably won't trigger anyway given it's DEFENSIVE miss recovery, meaning it's a tech that triggers when you're not doing the thing that it's supposed  to actually help with.
* Not 100% certain if crit_ok works for defensive techniques, as seen with Counter.

Overall, the style is generally a grabbag of abilities with no synergy or theme. Given its intended flavoring, it could either be reworked to resemble a modified, later-game version of Brawling, OR it could be reworked to explicitly be a mixed martial art, which would perhaps entail combining buffs and techniques from whichever martial arts seem logical for its founder (presumed to be one of the prepper NPCs) to be interested in.

Possible styles that could be drawn upon for inspiration, if the latter is attempted:
1. Krav Maga is the definitive "whatever works" style, and would be an excellent foundation to tweak.
2. Judo would be a logical source of grappling-focused abilities to work into the style, with Pankration being a sensible but less-obvious second choice.
3. Boxing, Karate, and Taekwando are popular, well-known styles that might influence someone developing a post-apocalyptic combatives system.
4. Eskrima is likely the most logical choice of a weapon system for someone to incorporate into a constructed martial art, while Fencing would be another example justifiable by it being a popular style.
5. Medieval Swordsmanship and Fior de Battalgia might be reasonable things to incorporate into this style, but might not be as logical to a survivor.
6. Ninjutsu would warrant inclusion just for being exactly the sort of thing you'd expect the prepper NPCs to be interested in.

**Comment by adamkad1** [comment]
i though you just needed alloy plating for limb block

**Comment by chaosvolt** [comment]
Ah right, yeah. I'll need to see how that functions compared to biojutsu, however. If it only allows limb blocks with CBMs and that's actually intended then it's fine, but I'm not 100% if that's Noct's intention.

**Comment by adamkad1** [comment]
> Ah right, yeah. I'll need to see how that functions compared to biojutsu, however. If it only allows limb blocks with CBMs and that's actually intended then it's fine, but I'm not 100% if that's Noct's intention.

yeah would make sense

**Comment by chaosvolt** [comment]
Had some discussion with Hymore on discord and evidently not gaining blocks at a sane level does indeed hinder getting bionic blocks.
