### ISSUE TITLE
Bio-Weapon Lab/ Makeshift Command Centre Crashing

### ISSUE THREAD

**Issue by OhDC** [Noctifer-de-Mortem/nocts_cata_mod#131]
Approached a Bio-Lab in my current long term game and crashed out

Made a new world with Cata++ as the only mod and started fresh at the bio lab, crashed on trying to move a single space.

On the latest experimental (9815), using the most recent Cata++ from this git, haven't tried other previous versions.

This is from the crash.log if it helps;

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8867-g8ca757d
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:
    @0x5C56C5[cataclysm-tiles.exe+0x1C56C5]
    @0x5C6192[cataclysm-tiles.exe+0x1C6192]
    raise+0x21B@0x7FFAA13DAE7B[msvcrt.dll+0x2AE7B]
    abort+0x1B@0x7FFAA13DF28B[msvcrt.dll+0x2F28B]
    IMG_LoadWEBP_RW+0xFDD01@0x1194321[cataclysm-tiles.exe+0xD94321]
    IMG_LoadWEBP_RW+0xFDDE7@0x1194407[cataclysm-tiles.exe+0xD94407]
    @0x7A627B[cataclysm-tiles.exe+0x3A627B]
    @0x7C6307[cataclysm-tiles.exe+0x3C6307]
    @0xD1C97A[cataclysm-tiles.exe+0x91C97A]
    @0xA1A4B8[cataclysm-tiles.exe+0x61A4B8]
    @0xB7CC61[cataclysm-tiles.exe+0x77CC61]
    @0xB826ED[cataclysm-tiles.exe+0x7826ED]
    @0x6FBAD2[cataclysm-tiles.exe+0x2FBAD2]
    @0x6FD26C[cataclysm-tiles.exe+0x2FD26C]
    IMG_LoadWEBP_RW+0x612598@0x16A8BB8[cataclysm-tiles.exe+0x12A8BB8]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFAA1487BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFAA1A4CED1[ntdll.dll+0x6CED1]

If theres any other info I can provide please let me know

EDIT: Found a Makeshift Command Centre and also crashed

**Comment by chaosvolt** [comment]
I'll have to check whether all the recent "everything is crashing" bugs have been resolved lately, because I have no way to figure out whether this is really a Cata++ thing or a CDDA thing.

**Comment by OhDC** [comment]
Just wanted to add a note that I debug killed the "bio hunter" NPC and was able to move around freely in the bio lab without crashing, but searching that NPC caused the same crash as before.

**Comment by chaosvolt** [comment]
Ah, that helps. I'll grab a recent build later on when I get the chance to, and poke around to see if I can figure out a possible cause.

**Comment by chaosvolt** [comment]
Yep, something with the NPCs is triggering this either when they move or when you go to their dropped items. The usual suspect is the guns, which have been a giant pain in the ass for about a year straight at this point. However, I debug spawned in the laser weapons and found they weren't doing anything weird.

However! I have reasonable suspicuon that https://github.com/CleverRaven/Cataclysm-DDA/issues/35117 is somehow to blame. You see, the guns spawned on Evy and the bio-weapons all start with bayonets installed. This is a holdover from when I discovered that NPCs will use UPS weapons if they have a bayonet, up until UPS weapons started causing NPCs to crash the game no matter what.

I'm about to test whether removing the bonus gunmod they start with fixes this..

**Comment by chaosvolt** [comment]
Yep, it's a CDDA bug caused by nonsensical gunmod behavior, I'll have a PR up in a bit since these added gunmods are no longer vital to getting the NPCs to fire their weapons.
