### ISSUE TITLE
Cata++ conflicts with Classes and scenarios mod

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [Noctifer-de-Mortem/nocts_cata_mod#14]
Error: Duplicate entries in the profession array.

**Comment by chaosvolt** [comment]
The professions don't override as expected? Odd.

**Comment by Noctifer-de-Mortem** [comment]
I see, will take a look when I am able to.

**Comment by chaosvolt** [comment]
Found it. Seems literally just removing the cykotic profession from the extension of Experiment scenario is enough to fix it, but I'd want to ask @BorkBorkGoesTheCode to keep us informed of any PRs to CDDA that further flesh out More Classes and Scenarios.
