### ISSUE TITLE
Biojitsu stance - C++ code in game window

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Noctifer-de-Mortem/nocts_cata_mod#150]
See this for more info

![whut](https://user-images.githubusercontent.com/3938423/71448522-26765900-273d-11ea-8e7a-076c7b7315c1.png)

**Comment by chaosvolt** [comment]
Biojutsu is a vanilla martial art, not a Cata++ one.

This is deliberate psuedocode in the buff descriptions actually, see here: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/martialarts_fictional.json#L17
