### ISSUE TITLE
Stunlock due to getting zapped on counters while using Survivor Combatives art

### ISSUE THREAD

**Issue by DillonSimeone** [Noctifer-de-Mortem/nocts_cata_mod#153]
[save.zip](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/files/4008904/save.zip)

Save is attached.

Broken limbs, and dead tired. Keep getting zapped by super scout attacking me while attacking which was pushing my movement further and further down into the negatives making it impossible for me to take an action.

It took about three hours for the zombies to finally do me in. 

When I looked into the character's save file, I noticed this snippet:
"player": { "moves": -581, "pain": 298, "effects": ...

Mod list:
[
  "dda",
  "no_npc_food",
  "magiclysm",
  "aftershock",
  "crt_expansion",
  "FIC_Weapons",
  "growable-pots",
  "ew_pack",
  "makeshift",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "nw_pack",
  "alt_map_key",
  "Cata++",
  "Mining_Mod",
  "my_sweet_cataclysm",
  "MMA",
  "vamp_stuff",
  "Arcana",
  "vamp_stuff+arcana",
  "more_locations",
  "No_Rail_Stations",
  "deoxymod",
  "blazemod",
  "Heavy miners",
  "Tanks",
  "necromancy",
  "Arts' Guns",
  "no_religious_Texts",
  "novitamins",
  "speedydex",
  "secronom",
  "stats_through_kills"
]

**Comment by DillonSimeone** [comment]
Playing on build 1089. Escaped the stunlock by editing the save file to have my character to be moved outside of the house to the right. T

**Comment by chaosvolt** [comment]
Sadly this is a vanilla issue with all monsters with zapback, compounded with how your speed was likely severely tanked. I'd suggest reporting it to CDDA itself, as the only likely cause here is something vanilla monsters can do too.

If anything, compared to regular zapback monsters, I'm surprised that a character could last long enough getting pummeled while stunlocked, as the zombie super-soldiers are pretty nasty in close combat.
