### ISSUE TITLE
Heavy and medium mil armor has the same materials

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [Noctifer-de-Mortem/nocts_cata_mod#16]
Both have Kevlar and leather and have identical protection. Their protection is also weak.

**Comment by chaosvolt** [comment]
Oof. Any recommendations for protection then?

**Comment by BorkBorkGoesTheCode** [comment]
Thickness 7 for the medium armor, 8 for the heavy armor.

**Comment by chaosvolt** [comment]
Sounds decent. No changes to the light variant, I assume?

**Comment by BorkBorkGoesTheCode** [comment]
I'm wondering if buffing cut and bash resistance given by kevlar and dropping sturdy quality from all ballistic vests here and in coregame would be a good idea.
