### ISSUE TITLE
Shooting the Survivor's Fighting bow against electric enemies triggers zapback

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [Noctifer-de-Mortem/nocts_cata_mod#17]
https://discourse.cataclysmdda.org/t/shockers-zap-you-if-bow-conducts-electricity/15586

**Comment by chaosvolt** [comment]
That sounds like a hardcoded bug, not a mod issue. Are they certain that reach flag is the issue?

**Comment by BorkBorkGoesTheCode** [comment]
According to Kevin it's a hardcoded bug in reached attack.
