### ISSUE TITLE
Issue with loading up

### ISSUE THREAD

**Issue by Jninja1** [Noctifer-de-Mortem/nocts_cata_mod#179]
I don't know if anyone is having this issue, but when I tired to load my game after the launcher's update it gave me this error message.

 DEBUG    : Error: data/mods//nocts_cata_mod-master/Surv_help/c_martialarts.json: line 27:27: tried to start object, but found '[', not '{'

        "buff_duration": 1,
        "bonus_dodges": 1,
        "flat_bonuses": [ [
                          ^
                            "dodge", "int", 0.25 ] ]
      }
    ],

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1099
I guess the launcher has a new way of reading?

**Comment by chaosvolt** [comment]
JSON change to martial art stuff actually, will have a fix up in a bit.
