### ISSUE TITLE
Bug when creating a new character, or loading a save

### ISSUE THREAD

**Issue by crazykid080** [Noctifer-de-Mortem/nocts_cata_mod#182]
It appears to be related to the newest experimental build (10490) that removed anesthetic kits

` DEBUG    : Error: line 99:18: no such item

        { "item": "laser_rifle", "x": 12, "y": 11 },
        { "item": "goggles_welding", "x": 4, "y": 20, "repeat": 1 },
        { "item":
                 ^
                  "anesthesia", "x": [ 11, 12 ], "y": 19, "chance": 50, "repeat": 3 }
      ],
      "place_npcs": [ { "class": "bio_hunter", "x": 5, "y": 21 } ],

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 816
`

**Comment by miradosamurai** [comment]
I have the same problem, and used Notepad++ to do some digging.

"anesthesia" shows up 6 times across 4 files:
lines 437 and 533 in \Surv_help\c_item_groups.json
line 230 in \Terrain\Bio_Weapon_Lab.json
lines 207 and 735 in \Terrain\mapgen_obsolete.json
and line 494 in \Terrain\Unknown_Lab.json

Until the mod is updated you can work around this by just deleting these lines (making sure to get any related commas), and the game should load, though I don't know if this will hurt any saves after an update, though I doubt it. I am getting another error about a 454 speedloader, but as far as I can tell that doesn't have anything to do with this mod, and I can just continue past it.

If you don't want to delete them yourselves here is a copy of the ones I edited, you should just need to open the zip and copy the folder inside into your mod folder and replace the old files.
[nocts_cata_mod-master.zip](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/files/4433849/nocts_cata_mod-master.zip)

**Comment by chaosvolt** [comment]
Just saw this, will yeet a PR at Noct in a bit.
