### ISSUE TITLE
Been getting this id issue at startup

### ISSUE THREAD

**Issue by sakarax** [Noctifer-de-Mortem/nocts_cata_mod#200]
DEBUG    : Error: data/mods//nocts_cata_mod-master/Char_creation/c_start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "id": "surv_camp_l",
    "name": "Survivor Camp Site",
    "terrain": [ "surv_camp" ]q

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

Been trying to start up a fresh install of Cataclysm + mods... didn't find any errors similar to this on my very (brief) look so apologies if this has already been addressed

**Comment by chaosvolt** [comment]
Update Cataclysm++, reminder that the launcher does not update third-party mods for you, and that hitting "update game" only affects CDDA itself and its in-repo mods. If you're using experimental CDDA, I recommend you download it from the main page. If you're using 0.D Stable, 0.E Stable, or 0.E Experimental build 10614, check the releases section.
