### ISSUE TITLE
I have cata++ but ive also used the noct cata mod...they are separate for me

### ISSUE THREAD

**Issue by Demonheim** [Noctifer-de-Mortem/nocts_cata_mod#224]
I obviously have an outdated one so I dont know if this is relevant but here you go.
![cataplusplus2](https://user-images.githubusercontent.com/42292405/99721159-62f92480-2a74-11eb-954f-67ca7be3d0be.png)
![cataplusplus1](https://user-images.githubusercontent.com/42292405/99721165-655b7e80-2a74-11eb-8766-0b05eaeeb9b9.png)

**Comment by chaosvolt** [comment]
The folder name is `nocts_cata_mod`. The ID assigned in the modinfo file is `Cata++`. That doesn't appear to be the actual problem here. I'm going give this a quick check, it looks like possibly UPS-based weapons no longer need the old NO_AMMO flag.
