### ISSUE TITLE
Error when creating new character- Build 11358 Experimental

### ISSUE THREAD

**Issue by SetArk** [Noctifer-de-Mortem/nocts_cata_mod#239]
Hoy, CATA is dropping this error and crashing the game right after.
-
 DEBUG    : Error: Json error: mods/nocts_cata_mod_DDA/Terrain/Unknown_Lab.json:491:18: no such item type 'acs_74_stealth_cloak_off'

        { "item": "blood_m", "x": 14, "y": 15 },
        { "item": "blood_p", "x": 15, "y": 15 },
        { "item":
                 ^
                  "acs_74_stealth_cloak_off", "x": 18, "y": 7 },
        { "item": "megamap", "x": 18, "y": 7 },
        { "group": "guns_milspec", "x": [ 0, 1 ], "y": 9, "chance": 50, "repeat": 3 },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 861
-

**Comment by chaosvolt** [comment]
Woops. Looks like an oversight caused by https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/238, due to Unknown Labs accidentally still spawning a version that was supposed to be obsolete.
