### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blackwolf602** [Noctifer-de-Mortem/nocts_cata_mod#241]
DEBUG    : Error: Json error: data/mods/nocts_cata_mod_BN/Monsters/c_monsters.json:354:100: invalid monster flag: "BLEED"

    ],
    "death_drops": "mon_zombie_bio_knife_death_drops",
    "flags": [ "SEES", "HEARS", "SMELLS", "POISON", "NO_BREATHE", "FILTHY", "PATH_AVOID_DANGER_1", "
                                                                                                   ^
                                                                                                    BLEED" ],
    "delete": { "upgrades": { "half_life": 28, "into": "mon_zombie_bio_knife" } }
  },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 861

**Comment by chaosvolt** [comment]
Use the correct version of the mod with the version of the game you're using. If you're using DDA, use the DDA version, not the BN version.
