### ISSUE TITLE
Failed Bioweapon no longer availabe in lab escape scenario

### ISSUE THREAD

**Issue by meelock** [Noctifer-de-Mortem/nocts_cata_mod#244]
The failed bio-weapon profession is no longer in the lab escape scenario options, likely because they changed the ID of the scenario.
IMO, the failed bio-weapon profession is only useful in this scenario, as in the bio-weapon lab, there are other professions that would always be chosen before it.

**Comment by chaosvolt** [comment]
Weird. Will poke around with it in a bit.

**Comment by chaosvolt** [comment]
...can't reproduce this.

![image](https://user-images.githubusercontent.com/11582235/108290326-c23f0180-7155-11eb-86cf-6445aa6e83eb.png)

Did you pick the Lab Staff scenario instead of Lab Patient? If so, you would've seen the super soldier professions added to the profession lists, but not failed bio-weapon for obvious reasons.

**Comment by meelock** [comment]
This might actually have to do with kenan's modpack, I'll see if I can reproduce it there.

**Comment by meelock** [comment]
In kenan's pack it is renamed "challenge-lab" rather than "challenge-lab escape" 
![image](https://user-images.githubusercontent.com/6434568/108298615-1cd65e80-7152-11eb-961c-69aa34ecfa92.png)
And it has the default playable characters:
![image](https://user-images.githubusercontent.com/6434568/108298674-31b2f200-7152-11eb-9dcb-044070e81c70.png)

**Comment by meelock** [comment]
Found the culprit:
```
[
  {
    "type": "scenario",
    "id": "lab_chal",
    "name": "Challenge-Lab",
    "points": -8,
    "description": "You've been locked in a lab with no (obvious) way out!  Find a way to escape or starve to death.",
    "start_name": "Locked Lab",
    "professions": [ "unemployed", "mutant_patient", "mutant_volunteer", "labtech", "broken_cyborg" ],
    "allowed_locs": [ "sloc_lab_escape_cells", "sloc_lab_finale", "sloc_ice_lab_stairs", "sloc_ice_lab_finale" ],
    "traits": [
      "ELFAEYES",
      "URSINE_EYE",
      "FANGS",
      "GILLS",
      "SPINES",
      "PLANTSKIN",
      "NAILS",
      "RADIOGENIC",
      "PADDED_FEET",
      "RAP_TALONS",
      "HOOVES",
      "CANINE_EARS",
      "FELINE_EARS",
      "TAIL_FLUFFY",
      "TAIL_LONG",
      "WEB_WALKER",
      "WHISKERS",
      "SLIT_NOSTRILS",
      "TROGLO",
      "WEBBED",
      "BEAK",
      "UNSTABLE",
      "RADIOACTIVE1",
      "SLIMY",
      "HERBIVORE",
      "CARNIVORE",
      "PONDEROUS1",
      "SUNLIGHT_DEPENDENT",
      "COLDBLOOD",
      "GROWL",
      "ARM_FEATHERS",
      "ARM_TENTACLES",
      "LEG_TENTACLES",
      "CHAOTIC",
      "ALCMET",
      "LIGHT_BONES",
      "CHITIN"
    ],
    "flags": [ "CHALLENGE", "CITY_START" ]
  }
```
A mod called "mutation changes."

**Comment by chaosvolt** [comment]
Use the source whenever possible. Shit like this is why I advise against using mod compilations whenever possible, it causes weird desnyc and confusion over the source of a problem.

FFS I'm fairly certain the split in the lab scenario is SEVERAL months old. It's pre nested containers at minimum, as BN has the same split.
