### ISSUE TITLE
Update Evelynn's mutation

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Noctifer-de-Mortem/nocts_cata_mod#250]
Should work on giving Evelynn and the other super soldier NPC classes the new Sentinel traits.

**Comment by chaosvolt** [comment]
Oh yeah, I can work on that. I'm guessing a bio-hunter would be, to some extent, a hybrid of scout and bio-engineer? Or should she have the standard augmentations as only one of those classes?

**Comment by Noctifer-de-Mortem** [comment]
Solved by #251
