### ISSUE TITLE
Survivor Scout suit and Survivor Armoured Scout Suit Not covering arms

### ISSUE THREAD

**Issue by Bobito-Gonzales** [Noctifer-de-Mortem/nocts_cata_mod#252]
Hey! Great mod first of all.

Now, this might be by design, but it still seems oddto me. The survivor scout suit and armored scout suit both cover basically everything with a 100% coverage (Both legs, both feet, both hands, torso and head), EXCEPT the arms, which they dont cover at all.

For now I've just edited the Jsons files, but if it is not by design it might be worth updating the mod files on the repository,

Thanks

**Comment by chaosvolt** [comment]
Ah, weird. It has `ARMS` in the BN version, but looks like when converting the bodypart IDs for the DDA version the arms got forgotten. Will fix in a second.
