### ISSUE TITLE
Build #11552 Im getting this error when creating a character

### ISSUE THREAD

**Issue by WildRufus** [Noctifer-de-Mortem/nocts_cata_mod#255]
DEBUG    : (json-error)
Json error: data/mods/nocts_cata_mod_DDA/Monsters/c_monstergroups_modcompat.json:6:16: Invalid or misplaced field name "override" in JSON data

    "type": "monstergroup",
    "default": "mon_null",
    "override":
               ^
                false,
    "auto_total": true,
    "monsters": [

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122

Modlist:
![image](https://user-images.githubusercontent.com/81764809/113316465-a7dc7400-930e-11eb-89f3-0e7f384d7f24.png)

**Comment by chaosvolt** [comment]
Damn, I'm guessing mod-interaction itemgroup stuff doesn't behave as well as I thought it did when

Bare minimum, it seems fine in BN when I test it, suggesting it's one of those skippable-load-error things DDA added that sometimes breaks shit that shouldn't be an error.

**Comment by chaosvolt** [comment]
Sorry for not getting to this sooner. Yep, looks like it's a skippable load error affecting only the two monstergroups that're normally only defined in PK's Rebalance.
