### ISSUE TITLE
Fix mutation categories

### ISSUE THREAD

**Issue by ZhilkinSerg** [Noctifer-de-Mortem/nocts_cata_mod#26]
Default values were removed from `threshold_mut`, `mutagen_message` and `iv_message` nodes, so mutation categories MUST set them explicitily - see https://github.com/CleverRaven/Cataclysm-DDA/pull/24183 for details.

**Comment by chaosvolt** [comment]
Will set up a PR if Noct doesn't see this by then. Ooh right, and I'll need to update Arcana with this, I suspect.

```
Cleaned up categories. Previously:
id: "mutation_plant"
category: "PLANT"
category_full: "MUTCAT_PLANT"
mutagen_flag: "MUTAGEN_PLANT"
```
Will this also warrant changes?

**Comment by ZhilkinSerg** [comment]
Yes, if you used those nodes.

**Comment by chaosvolt** [comment]
Hmm. And if you added new mutatgen items, citing new mutation categories with new thresholds, will the old handling break?
