### ISSUE TITLE
UPS-powered energy weapons throwing error

### ISSUE THREAD

**Issue by AdamChirnside** [Noctifer-de-Mortem/nocts_cata_mod#264]
Using a UPS energy weapon seems to throw an error, attached at the end of this report.
I am also using the UPS Bionic, in addition to UPS item in inventory.

Steps to reproduce:
1. Equip UPS-fed NEO-33
2. Move near enemies/start shooting

 
 DEBUG    : can't set ammo null in NEO-33 laser pistol as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 549

**Comment by AdamChirnside** [comment]
In addition, my NEO-33 has become fouled after prolonged use.

**Comment by chaosvolt** [comment]
Are you using the latest version of the mod with latest version of either DDA or BN? And are you using the correct version of the mod with the correct version of Cataclysm?

**Comment by AdamChirnside** [comment]
I'm using the latest version of the mod with latest Experimental DDA.
Strangely though, I started a new game to try and recreate the issue but it won't show up there?

**Comment by chaosvolt** [comment]
That makes me suspect it might've been a case of using the BN version in DDA, but if that's the case it should've failed to start up entirely. I'll grab the latest builds and test them out, in a bit.

**Comment by chaosvolt** [comment]
Bit belatedly, just tested it in build 2021-05-17-0755, and got the error. Then grabbed latest available build (2021-05-23-0814) and tested it, got the same error message.

```
 DEBUG    : can't set ammo null in NEO-33 laser pistol as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 549
```

I'll check to see if the JSON for the NEO-33 is different from the other UPS weapons, but if it can't be consistently reproduced that suggests it's a nested container bug of some sort.

**Comment by chaosvolt** [comment]
Okay never mind. You need to go report this as a CDDA issue: https://github.com/CleverRaven/Cataclysm-DDA/issues

Tested this with the vanilla A7 laser rifle and got the same thing:
```
 DEBUG    : can't set ammo null in A7 laser rifle as it is not an ammo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 549
```
