### ISSUE TITLE
Modinfo.json error in Cata Master.zip mod version download

### ISSUE THREAD

**Issue by JhinKisunagi** [Noctifer-de-Mortem/nocts_cata_mod#265]
Much like it sounds, there is a ‘value’ error that is causing CDDA itself to not find/cannot find the mod in question, as the tag itself is simply missing 3 letters to it.   While I might be able to fix it if I had the means to access it and edit it, I don’t know the entire ruling of it it’d be allowed or if it’d muck things further, if for some reason there is other stuff that would have to be edited to fix this.  I’m very very inept at coding, and I’d rather somebody with either better knowledge and experience (and also the means to fix it.) do so, as it reduces risk of something else borking if this is beyond just a simple fix (which I don’t think it’d be beyond adding those 3 letters, but what do I know.. lol.)

CDDA looks for the value of ‘ident’ when looking for ‘mods’ etc, for category and so it can find and load them.  With the current update to the file as of May 21st, that value in the mods json file is set as ‘id’ NOT ‘ident’.

Pics below for it.

![ED17CA6E-6CF3-4ED0-B56C-FF68076DFA2C](https://user-images.githubusercontent.com/84940811/119904791-8a8fe480-bf10-11eb-8c51-0fac46a14975.jpeg)

![FD65F8AD-A0FA-4AB7-892F-7E4BB477B8FB](https://user-images.githubusercontent.com/84940811/119904077-5c5dd500-bf0f-11eb-8a6a-9f8ca7b4ce95.jpeg)

I would like to include that, before updating the mod, the issue was not there, as the json had the value set as ‘ident’.  Currently the new version has that set to a ‘id’.  So it cannot find or load it, and is creating an error.   Everything is up to date, and up to par.

For the folder in question is from the one below, in the download for the MASTER.zip

![A3AD9482-D839-4A1B-AEC9-626C4A87AAF1](https://user-images.githubusercontent.com/84940811/119904201-9333eb00-bf0f-11eb-9e3c-06502dcfbe76.jpeg)
![FD69A2D1-D32B-4DFA-A9BB-1B8E3159F750](https://user-images.githubusercontent.com/84940811/119904206-95964500-bf0f-11eb-955f-24b708dd82e4.jpeg)

**Comment by chaosvolt** [comment]
I'm not sure how up to date the mobile versions of Cataclysm are, but that seems to be an issue where the version you have predates this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/39332

That was merged almost a year ago, so that suggests that either you haven't updated CDDA in a while, or whoever is in charge of setting aside the mobile version hasn't been doing that in forever.

**Comment by JhinKisunagi** [comment]
Quite the contrary, the version was updated as of 7 days ago.  The file itself that needs fixed is just a simple add of ‘ent’ to the current ‘id’.   The previous person who had updated CDDA before Appolov on iOS was dancingbottle, who hadn’t updated for a few years.


Fast forward nearly 4 years now (to current time) and the version went from Cooper, to ..whatever the E is.  I call it Epsilon cuz I cannot ever seem to recall it exactly.  But, not the point.   Version was updated a week ago.  This issue I had as of yesterday.  Which was caused by the modinfo.json file in question having the value *id* and not *ident* which is what the mod version BEFORE I UPDATED CATA++ was using.


Currently the json with the recently updated file from CATA++ is as you can see in the pics above, listed as *id* not *ident.*. That particular error is from the Cata++ not being found because the mod has an incorrect value and as such is not able to be located.   Or at least, it is, but cannot load it, because the value is missing the 3 letters of *ent*.


You can go and download the file yourself if you don’t believe me.   But whenever I take the mod OUT, I have NO ERROR.  But if I place it in the folder where it meant to go, I get the error.   It’s a, afaik, simple fix to just adding 3 letters to the modinfo.json to remedy the error.   So that it’ll properly read as *ident*.

**Comment by chaosvolt** [comment]
So it's using 0.E stable, and you're trying to use a version of the mod that's for 0.E experimental builds. That's the problem right there, the PR that removed all the old uses of `ident` in favor of consistently using `id` for everything was opened and merged during 0.E experimental builds, which means after 0.E stable.

Use the 0.E stable release for that, if it's feasible on mobile: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases
