### ISSUE TITLE
Nano-Mutagenic Serum crafting does not work with batteries (BN)

### ISSUE THREAD

**Issue by mkikt4743** [Noctifer-de-Mortem/nocts_cata_mod#279]
Nano-Mutagenic Serum crafting does not work with batteries, but works with the cobalt-60 pellet. Testing performed in a world with Dark Days Ahead, No NPC Needs, and Cata++. Note this is the version that ships with Kenan's Modpack.

Attempting to craft with batteries only and all other parts:

![screen1](https://user-images.githubusercontent.com/56452763/123892386-792f6300-d928-11eb-9991-dcdf6ee21b2b.png)

Note that crafting with a cobalt-60 pellet works as intended.
Debug Game Report:
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: ddb7a8d [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++]
]

**Comment by chaosvolt** [comment]
Test it in Bright Nights as well. That sounds like some sort of nested containers type of code fuckery again.

**Comment by mkikt4743** [comment]
This was tested in Bright Nights.

**Comment by chaosvolt** [comment]
Ah, okay. Weird, I'll work on a fix for this later today.

**Comment by mkikt4743** [comment]
Appreciate it.
