### ISSUE TITLE
Tried to start new game and got this error. Experimental DDA 6616372

### ISSUE THREAD

**Issue by daniilsan347** [Noctifer-de-Mortem/nocts_cata_mod#281]
DEBUG    : Error: Json error: data/mods/nocts_cata_mod_DDA/Terrain/Mapgen_Variants.json:135:18: no such item type 'm4a1'

        { "item": "stanag50", "x": 12, "y": 12, "chance": 75, "repeat": 20 },
        { "item": "556", "x": 14, "y": [ 9, 12 ], "chance": 75, "repeat": 150 },
        { "item":
                 ^
                  "m4a1", "x": 16, "y": [ 9, 11 ], "magazine": 100, "chance": 75, "repeat": 36 },
        { "item": "stanag30", "x": 16, "y": 12, "chance": 75, "repeat": 100 },
        { "item": "556", "x": 18, "y": [ 9, 12 ], "chance": 75, "repeat": 150 },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 863
 VERSION  : 6616372

**Comment by chaosvolt** [comment]
Looks like that's due to https://github.com/CleverRaven/Cataclysm-DDA/pull/46814 changing item IDs as a consequence. Setting aside a 0.F release now, then will PR a fix.
