### ISSUE TITLE
Json error when creating custom character.

### ISSUE THREAD

**Issue by ViergieSP** [Noctifer-de-Mortem/nocts_cata_mod#289]
```
DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/mods/nocts_cata_mod_DDA/Monsters/c_monster_override.json:65:23: expected string but got '{'

    "special_when_hit": [ "RETURN_FIRE", 100 ],
    "death_drops": {  },
    "death_function": {
                      ^
                        "corpse_type": "BROKEN" },
    "flags": [ "SEES", "NOHEAD", "ELECTRONIC", "COLDPROOF", "IMMOBILE", "NO_BREATHE" ],
    "anger_triggers": [ "PLAYER_CLOSE", "HURT", "FRIEND_ATTACKED", "FRIEND_DIED" ]


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 865
```

I'm using experimental version (212b6d8, i'm on andorid) with Disable NPC Needs and Bionic Professions mods. I haven't change any other settings. (I'm also still new with this game)

**Comment by chaosvolt** [comment]
That means the android version is painfully out of date. It's due to JSON changes made to not break due to this PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/49439

**Comment by DataRogue** [comment]
I'm seeing the same issue on the latest stable.

**Comment by chaosvolt** [comment]
Use the correct release for 0.F Stable: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases/tag/0.F

**Comment by DataRogue** [comment]
Ah, I think there must an issue with Installer not pulling the latest version correctly.

**Comment by chaosvolt** [comment]
Almost certainly when it comes to DDA, the launcher is very finicky and not newbie-friendly in the slightest.
