### ISSUE TITLE
Json error in latest experimental.

### ISSUE THREAD

**Issue by ifffrt** [Noctifer-de-Mortem/nocts_cata_mod#291]
Hey heads up. I just updated to the latest experimental and it seems to have broken the c_armor.json file. Fixing it is pretty simple though. You just need to add "max_charges": 100 to the items that needs it.

**Comment by chaosvolt** [comment]
![image](https://user-images.githubusercontent.com/11582235/128097761-c42c69b9-2ffc-40ce-ba40-f133d87ccbb9.png)

Now I'm not so sure that proposed fix is correct.

**Comment by chaosvolt** [comment]
Testing it now, think I've figured out a fix.

**Comment by ifffrt** [comment]
That's weird. I was playing on 0939 as well. I'm still playing fine with the fix.

![New Bitmap Image (5)](https://user-images.githubusercontent.com/74819253/128120123-99136aab-fe69-4651-b4d4-13346614504c.png)

**Comment by chaosvolt** [comment]
Well, it seems to work with the changes I implemented, so hmm.
