### ISSUE TITLE
This a little embarrassing

### ISSUE THREAD

**Issue by Howclumsy1** [Noctifer-de-Mortem/nocts_cata_mod#336]
![Screenshot (36)](https://user-images.githubusercontent.com/97034466/147935442-a0d7872b-b1ca-436d-a7bd-1bcffb7c3c3c.png)
Uhm is hard to explain but how this happen and could I fix it by myself. I'm really sorry if my language confused people

**Comment by chaosvolt** [comment]
You're using current version of Cata++ with 0.F stable version of DDA.

Use the correct version: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases/tag/0.F
