### ISSUE TITLE
Pnuematic LMG ammo error?

### ISSUE THREAD

**Issue by PeriodicOccupancy** [Noctifer-de-Mortem/nocts_cata_mod#345]
![image](https://user-images.githubusercontent.com/64710740/150082477-0c584ff2-10c4-4596-a8ce-142125ed02cd.png)
![image](https://user-images.githubusercontent.com/64710740/150082558-69dce4ff-52da-4e93-8c88-7d025ac623c8.png)

The first image is on world load the second is when I select the recipe for the Pneumatic LMG this is on 0.F-3 stable branch

**Comment by chaosvolt** [comment]
Double-check that you're using the correct version first: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases/tag/0.F

**Comment by PeriodicOccupancy** [comment]
That's the version I just downloaded and installed a few hours before making this post

**Comment by chaosvolt** [comment]
Odd. I'll work on testing this in a bit and see if I can chunk a 0.F-3 update at Noct, I guess. Though at this rate 0.F is so wildly out of date that using latest experimental or BN might be better, and DDA's evidently working on a new stable anyway.

**Comment by PeriodicOccupancy** [comment]
Alright, It's up to you I just thought I'd make a bug report about it. I was actually thinking after my current run ends that I'd probably move on to experimental anyway, had no idea they were already working on a new stable though, seems wild to me doesn't seem like that long since the last stable.

**Comment by chaosvolt** [comment]
No worries, just gotta get time to test things.

**Comment by chaosvolt** [comment]
https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases/tag/0.F-3 should fix things.

**Comment by PeriodicOccupancy** [comment]
![image](https://user-images.githubusercontent.com/64710740/150464418-ca8cc367-9568-4d47-b5d9-51272c4d5b02.png)

Fix seems to work, no errors on launch or selecting lmg in crafting, and ammo shows up as it should in the recipe's item description (had no ammo info before as if it was a melee weapon only)

what fixed it if you don't mind me asking? there's some old mods with similar issues I'd like to fix the ones that add the old scrap weapons back

**Comment by chaosvolt** [comment]
Turns out it was missing pocket data, easy fix. Hadn't come up before, but if I recall pocket data was optional for internal-magazine guns when the nested containers system first got shoehorned into also being used with guns.

**Comment by PeriodicOccupancy** [comment]
hmm guess its a different issue for the outdated mod then, anyway cheers and thanks for fixing, wouldn't have blamed you if you hadn't considering most people play on experimental now
