### ISSUE TITLE
Survivor Sabatons use wrong body part

### ISSUE THREAD

**Issue by DoctorGoat** [Noctifer-de-Mortem/nocts_cata_mod#347]
The Survivor Sabatons copy from boots_plate from the vanilla game, but the "armor" json tag includes the following:

"covers": [ "hand_l", "hand_r" ],

This leads to the player putting them on their hands and running around with boot fists.

I would have done a PR to fix it (it's literally just changing it to foot instead of hand) but I don't want to deal with git right now

**Comment by chaosvolt** [comment]
Pffft, whoops. Will PR a fix in a sec.
