### ISSUE TITLE
PARKOUR in Mutations

### ISSUE THREAD

**Issue by b3brodie** [Noctifer-de-Mortem/nocts_cata_mod#353]
PONDEROUS_BIOWEAPON cancels the removed PARKOUR trait
SPEED_BIOWEAPON cancels the removed PARKOUR trait

PARKOUR has been changed to a proficiency in experimental, leading to errors when referred to as a mutation.

**Comment by chaosvolt** [comment]
Whoops, forgot about that when implementing the DDA version.
