### ISSUE TITLE
Zombie augmented juggernaut (launcher version) never use it's launcher

### ISSUE THREAD

**Issue by waveyl** [Noctifer-de-Mortem/nocts_cata_mod#355]
Spawn a zombie augmented juggernaut, and watch it just runing with you.

**Comment by waveyl** [comment]
typo:
![image](https://user-images.githubusercontent.com/22638873/152759293-f18ca03a-8113-4373-b1ed-32852d335253.png)

**Comment by chaosvolt** [comment]
I've noticed it seems to not always use its launcher. They way it's set up now, it SHOULD fire but it only has 5 shots. I'll check the range and test in latest versions of BN and DDA in a bit when I can though.

**Comment by waveyl** [comment]
Addition: zombie super scout has the same problem.

**Comment by chaosvolt** [comment]
Is this in DDA, BN, or both?

**Comment by waveyl** [comment]
Just test on DDA

**Comment by chaosvolt** [comment]
I'll see if I can get time to test this, and if it's DDA-specific I'll try to see if there's some change that broke monster ranged attacks. I'm guessing then that vanilla turrets and the other augmented undead ranged attacks work?

**Comment by chaosvolt** [comment]
So I tested this a bit, the super scout and launcher juggernaut work fine in BN but not in DDA. The other augmented undead ranged attacks seem to work fine in DDA as well.

I'll check if there's any JSON difference between the BN and DDA versions, but if not this sounds like another case of DDA acting up in some way.

I'll have to check whether the .50 BMG turrets in vanilla DDA work or not, if I recall they're the one of the few DDA turrets to have the kind of full-targeting setup that closely matches how the scout and juggernaut are supposed to behave.

**Comment by chaosvolt** [comment]
AHAH. I figured out what it is. The weapons the monsters were using still relied on an old workaround of removing the `FIRE_X` flags to make them only consume 1 ammo per shot, because monster ranged weapons didn't use those flags correctly. I don't know if that behavior is still needed, but if so I need to replace them with an overriding `ammo_to_fire` instead.

**Comment by chaosvolt** [comment]
Hecc, forgot the misc typo fix though. @.@
