### ISSUE TITLE
NPC Evelyn becomes anemic and dies despite no bleeding

### ISSUE THREAD

**Issue by BranJun** [Noctifer-de-Mortem/nocts_cata_mod#359]
After this happened I used the debug menu to figure out why this happens, it seems she just loses blood and red blood cells for no reason. I think it's due to the Sentinel Physicality Mutation having a line of code saying
 "vitamin_rates": [ [ "blood", -1 ], [ "redcells", -1 ] ], 
I went to the command bunker and found all NPC with Sentinel Physicality  have this "bleeding" problem.

**Comment by BranJun** [comment]
Actually I changed the vitamin rates to negative in my files and that fixed it, for some reason they were positive in my game.

**Comment by chaosvolt** [comment]
Yeah this was fixed by https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/358
