### ISSUE TITLE
Bio-Weapons Lab Start Considerations

### ISSUE THREAD

**Issue by RodriguesCIA** [Noctifer-de-Mortem/nocts_cata_mod#361]
Fairly frequently, I am having Evelynn murdered by the Abominations upstairs just after she kills the zombies in the lab. Seems to be a matter of luck: if she engages them while they are fighting (the undead and the living, that is), she has the firepower to kill most of them and the health to tank the survivors. However, as that relies on LOS stuff, it is not entirely reliable. And if she dies, there's not a whole lot the player can do. If they are lucky, the Abominations (always the living ones, I presume they are tankier by virtue of regenerating) will be clustered somewhat far away, and a bit of running with a lot of praying ensures a somewhat lackluster, but viable game start. If the player isn't lucky, the cluster is right by the bunker door, and a tough fight for most Bio-Weapons if not straight up imposslbe is guaranteed. 

Considering that this lab must be the same as the labs that appear on the worldmap (otherwise there wouldn't be multiple Evelynn copies), the goal must be to make the exit from it more reliable, but not necessarily entering it. After all we don't want to make it an even more trivial loot safe for players than it already is. For this, I have two suggestions.

1 - Give Evelynn Dialectric Capacitance and make sure it is active. With this, she is about guaranteed to survive fighting the abominations, never getting more than roughed up, which currently, is about the best you can expect.

2 - Lab redesign. Essentialy, let's make a micro-sewer or hidden door leading to a passage leading to a manhole somewhat far away. That will also demand a bit of a redesign of the bunker at the entrance, at least so Evelynn can't hear the abominations and instantly try to fight them. Perhaps doubling the walls/doors?

**Comment by chaosvolt** [comment]
Hmm. Giving her that CBM might work, though I dunno if it's set to be usable by NPCs or not. Giving her a zone to limit her investigating is an option too.

**Comment by RodriguesCIA** [comment]
> Hmm. Giving her that CBM might work, though I dunno if it's set to be usable by NPCs or not. Giving her a zone to limit her investigating is an option too.

If it is not, a low level electric immune outfit should do. A damaged hazmat suit?

**Comment by chaosvolt** [comment]
Maybe, though it'd be awkward and probably clash with her current outfit. More stuff I'll have to test if Noct doesn't get any ideas.

**Comment by Noctifer-de-Mortem** [comment]
Evelynn has special NPC definitions before she is recruited, could maybe have her stay still and not investigate stuff while she is down in the lab?  Not sure if investigating stuff can be defined when setting s static NPC. She can be "locked" behind a door in the lab to avoid fighting and when you are looking inside the place you talk to her and have her help you fight your way out if you haven't killed enemies yet or just loot in peace if you have.

**Comment by chaosvolt** [comment]
If she has a faction assigned, then an investigate limit zone in the mapgen entry should be adequate for that.

**Comment by RodriguesCIA** [comment]
Some starts (specially Beta and Gamma, I believe) absolutely need her help to survive though, so completely locking her off might not be the best idea unless it is done smartly.

**Comment by chaosvolt** [comment]
Working on this now. Though Beta has Dielectric Capacitance and the Laser Gatling, so Beta is probably the best-suited of the four main bio-weapon professions for fighting augmented abominations.

You're right that Gamma would have serious trouble though, since they're the least combat-ready of the four fresh off the bat, but if they pick up the A7 in the bunker before they head upstairs they have a ranged option at least, since they have the UPS bionic. Delta is in a similar boat, not being as melee-ready as Alpha or Beta, not having an innate ranged bionic like Beta, but having the UPS bionic in a location that will always spawn a basic UPS-powered weapon in one of the side rooms.
