### ISSUE TITLE
"id": "mil_armor", encumbrance 

### ISSUE THREAD

**Issue by x7GoSu** [Noctifer-de-Mortem/nocts_cata_mod#363]
Don't know if this is intended or not, but the Military Amor encumbrance  is set at 44 . The light mil armor is at 12 then jumps to 44 for standard and drops back down to 36 for Heavy Armor.

**Comment by chaosvolt** [comment]
Yeah that's a whoops, it's supposed to be 24, as seen with the military helmet, and its encumbrance in the BN version.
