### ISSUE TITLE
Cannot get mutations form the nano serum

### ISSUE THREAD

**Issue by MikuMiddo** [Noctifer-de-Mortem/nocts_cata_mod#372]
I found this issue after I injected 5 nano serum and wait about 2 days but no mutations gotten.

Here is how I tested:
**1.Start a new character**
![image](https://user-images.githubusercontent.com/53809752/157636088-22c7f9b5-7ede-45bd-8989-4ce544817b19.png)
**2.Set mutagen and nano-mutagenic serum to 2500**
![image](https://user-images.githubusercontent.com/53809752/157636421-ab43fbbf-bacc-4e2f-9da1-3cf82cae5fbb.png)
![image](https://user-images.githubusercontent.com/53809752/157636440-0263d64a-e0d0-4709-b71d-a0df81fa3dde.png)
**3.Normally you will get mutations in 2 hour,but with nano serum it will onlt show you need more exotic mutagen**
![image](https://user-images.githubusercontent.com/53809752/157636948-64ff0e61-6d13-4d54-acb6-d48b98a8b11b.png)

The "重度纳米致突变暴露" in first picture means “Heavy Nano-mutagenic Exposure”

**Comment by chaosvolt** [comment]
More issues with the new mutagen mechanic, I suspect. It looks like it's triggering the mutation mechanics as intended, but still failing. At this rate I'd suggest giving Bright Nights a try.

I might look into the EOC stuff that came up when discussing https://github.com/chaosvolt/cdda-arcana-mod/issues/232 for Arcana, because this new mechanic seems incredibly fucky.

**Comment by chaosvolt** [comment]
Okay I've got good news and bad news. Good news is it doesn't seem to be specific to Cata++. Bad news is mutagen in general seems to be broken now.

@MylieDaniels waited a full 24 hours after having consumed both beast primer and beast mutagen, not a single mutation:
![image](https://user-images.githubusercontent.com/11582235/157727509-6d19a045-eead-434c-91d2-015bb1f347c9.png)

I double-checked to ensure that beast mutagen does indeed still give both the required vitamins and it does. I also tested Arcana's mutagenic stuff, which WAS working after the last fix I did, now they don't give mutations either. So something's definitely broken on DDA's end this time, unless mutation trigger rates have recently been massively nerfed.

Tested again on most recent available build just to be sure, same result. No mutations or mutation attempt messages after waiting 24 hours, after having taken both primer and the related mutagen.

**Comment by MikuMiddo** [comment]
> Okay I've got good news and bad news. Good news is it doesn't seem to be specific to Cata++. Bad news is mutagen in general seems to be broken now.
> 
> @MylieDaniels waited a full 24 hours after having consumed both beast primer and beast mutagen, not a single mutation: ![image](https://user-images.githubusercontent.com/11582235/157727509-6d19a045-eead-434c-91d2-015bb1f347c9.png)
> 
> I double-checked to ensure that beast mutagen does indeed still give both the required vitamins and it does. I also tested Arcana's mutagenic stuff, which WAS working after the last fix I did, now they don't give mutations either. So something's definitely broken on DDA's end this time, unless mutation trigger rates have recently been massively nerfed.
> 
> Tested again on most recent available build just to be sure, same result. No mutations or mutation attempt messages after waiting 24 hours, after having taken both primer and the related mutagen.

May you need more mutagen,only highly mutagen vitamins gives mutation.A primer only contains 400-500 mutagen,which is not enought for a mutation

**Comment by chaosvolt** [comment]
Hmm. I'd used both primer and mutagen, and last time I tested this that seemed to be enough to trigger it. I also found that nano-mutagen in Cata++ and the offerings in Arcana had been working last time I tested, when now they aren't.

It'll be a moot point not however, as I've sent Noct the above PR that'll fix this via not using the new mutagen mechanics at all.

**Comment by MikuMiddo** [comment]
> Hmm. I'd used both primer and mutagen, and last time I tested this that seemed to be enough to trigger it. I also found that nano-mutagen in Cata++ and the offerings in Arcana had been working last time I tested, when now they aren't.
> 
> It'll be a moot point not however, as I've sent Noct the above PR that'll fix this via not using the new mutagen mechanics at all.

the new mechanic is quite fun,but till now it seems have not been done yet,still using old is better for now

**Comment by MikuMiddo** [comment]
![image](https://user-images.githubusercontent.com/53809752/157810815-a017b83f-a08f-4f6b-ac66-3e3306687e35.png)
I tried with lastest version but still not get any mutations

**Comment by chaosvolt** [comment]
I just tested the PR in question. Are you using an out of date build?

**Comment by MikuMiddo** [comment]
> 

![image](https://user-images.githubusercontent.com/53809752/157811265-b065bcb5-b553-4b38-9737-06644781bc6b.png)
I am using the yesterday one.should I try the msvc one which build half hour ago?

**Comment by chaosvolt** [comment]
Worth a try, build I've been testing with was the 1719 build. Either way, I made sure that the EOC was working before I even committed. The only other thing I can think of to test is if you're testing on a fresh world/character or not, no idea if DDA can handle EOCs that only start existing after an update.

**Comment by MikuMiddo** [comment]
> 

![image](https://user-images.githubusercontent.com/53809752/157812839-137ee7ec-35f4-4bfb-9e5c-eb763c5e762d.png)
Yes,you are right.DDA cannot handle new EOCs after an update,you should creat a new world.A new character in old world is not enought.I should submit a issue to DDA

**Comment by chaosvolt** [comment]
Nice. Good luck with that, hope it goes well. Just now updated Arcana as well with a similar update. And now oughta call it a night.

**Comment by chaosvolt** [comment]
It was probably unwise to use a third-party mod as the primary example of this bug occurring, in the issue above.

You'll probably have to point out that even changes to vanilla EOC are going to be subject to this exact same issue of save incompatibility. Bringing an old save to a build that has new vanilla EOCs written will almost certainly trigger this too.

**Comment by MylieDaniels** [comment]
Okay, while I don't particularly feel like helping after the repeated insults to my work, here's the solution:
Use more mutagen.  It has a threshold for starting.
Nothing is broken, again.

**Comment by MikuMiddo** [comment]
> Okay, while I don't particularly feel like helping after the repeated insults to my work, here's the solution: Use more mutagen. It has a threshold for starting. Nothing is broken, again.

Yeap，looks they don't like you.Its not good to bring personal viewing to such a quiet huge open source project

**Comment by MikuMiddo** [comment]
> It was probably unwise to use a third-party mod as the primary example of this bug occurring, in the issue above.
> 
> You'll probably have to point out that even changes to vanilla EOC are going to be subject to this exact same issue of save incompatibility. Bringing an old save to a build that has new vanilla EOCs written will almost certainly trigger this too.

Yes,It should be easy to find one,I will try to catch one later

**Comment by chaosvolt** [comment]
> Use more mutagen. It has a threshold for starting.

Has the threshold changed since last time though? The reason I suspected it might be malfunctioning was because the same amounts of mutagen I had previously got to trigger the message were no longer doing so, at least I could've sworn I was able to get it triggering after https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/365 in Cata++ and https://github.com/chaosvolt/cdda-arcana-mod/commit/04bef04d5e3fbe15fdae81302998c5f1f03ab6ed in Arcana.

> Yeap，looks they don't like you.

I have nothing against them, they've been very helpful in terms of figuring out both the mutagen overhaul and how to figure out the basics or writing an EOC entry. I'm very grateful for that. My criticism so far has mostly just been with the code of the overhaul specifically, which does seem to have some flaws in implementation.

And even then, 90% of the problems I've had with it are either minor in the grand scheme of things, cases where it's just not clear at first how to get related JSON rather than a real flaw, or at worst easily worked around via other means if it actually is a legitimate problem to work with.

**Comment by chaosvolt** [comment]
Side note, I started up a character in 0.F-3 stable, ported it over to recent experimental, and I'm not able to reproduce https://github.com/CleverRaven/Cataclysm-DDA/pull/55233 at all, whether with vanilla mutagen or Cata++ nano-serum:
![image](https://user-images.githubusercontent.com/11582235/157999689-4c922965-98cc-4746-921f-a6d5c322419f.png)

So if EOCs do fail to update right after an update, it's not doing so in...uh, `cdda-windows-tiles-x64-msvc-2022-03-10-1719`.

**Comment by MikuMiddo** [comment]
> 
I kept tracking the lastest exp version and play the old save for 1 month，may one of them permanently damaged my save.But sadly I just deleted it just because of the bug.
So this may has been fixed just as a 'sideffect' of a PR,only a few version has it but can permanently effect your save.
