### ISSUE TITLE
Set GLARE in recipes to 1

### ISSUE THREAD

**Issue by YuPro** [Noctifer-de-Mortem/nocts_cata_mod#374]
In CDDA «glare protection» on all items was set to 1 in October.
In Cata++ we still have some recipes that use GLARE 2.

In c_recipes.json lines: 994, 1018, 1042, 1066.

Tried to make commit myself but looks like I need access from administrator.

Or you can give me permits and I'll push it.

**Comment by YuPro** [comment]
For Bright Nights it's not an issue since there are still 1-3 «glare protection» items there.

**Comment by chaosvolt** [comment]
The normal way to submit changes is to create a fork and make a pull request. I'll chuck an update at Noct in a second I guess.
