### ISSUE TITLE
AUTOCLAVE error

### ISSUE THREAD

**Issue by Maryionet** [Noctifer-de-Mortem/nocts_cata_mod#384]
![Screenshot_2022-05-06-16-26-24-93_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/167096316-86c13125-3724-4572-bf96-3c037d104c7f.jpg)

**Comment by chaosvolt** [comment]
Looks like cause is from https://github.com/CleverRaven/Cataclysm-DDA/pull/57007 removing the code for it. Will fix in the morning, need to get some sleep.

**Comment by chaosvolt** [comment]
That should do it, sorry for the delay.
