### ISSUE TITLE
<Bug> Expanded Digestion System CBM and Eater of the Dead Trait conflict

### ISSUE THREAD

**Issue by GexitheHundredth** [Noctifer-de-Mortem/nocts_cata_mod#389]
OS: Windows 11
Platform: Windows x64 (64-bit)
Branch: Experimental
Version: 5f60b52 (tiles)
Build: 2022-05-14-0602

I was testing out this mod for the first time and decided to pick the Bioweapon-ALPHA start, but in the character creation screen it says that Eater of the Dead is not compatible with the Expanded Digestion System CBM while both are included with the profession.

**Comment by chaosvolt** [comment]
This should fix it, looked into it and Expanded Digestion does all the things those traits do anyway: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/390
