### ISSUE TITLE
Surv_help Invalid or misplaced field error

### ISSUE THREAD

**Issue by Maryionet** [Noctifer-de-Mortem/nocts_cata_mod#398]
![Screenshot_2022-05-20-23-02-07-68_6fe8938556442e3d4f710ab4f9a16601](https://user-images.githubusercontent.com/68288642/169556993-9c18f90d-31b0-4c56-bf85-ac05f3a678f6.jpg)

**Comment by chaosvolt** [comment]
Spotted that while working on most recent update I chucked at Noct, so it ended up in there.
