### ISSUE TITLE
Can't place full-sized fridge, recipe calls for minifridge

### ISSUE THREAD

**Issue by vlad1492** [Noctifer-de-Mortem/nocts_cata_mod#413]
From: https://github.com/CleverRaven/Cataclysm-DDA/issues/58458

There is a old MIGRATION in the setting of Cata++

nocts_cata_mod_DDA/legacy.json Line 82
{
"id": "fridge",
"type": "MIGRATION",
"replace": "minifridge"
},

**Comment by chaosvolt** [comment]
Whoops. Guess by now it's probably safe to remove the migration.
