### ISSUE TITLE
NPC's in Makeshift Command Center do not retaliate when attacked, game marks them as both "Friendly" and "Attacking to Kill"

### ISSUE THREAD

**Issue by Eevim** [Noctifer-de-Mortem/nocts_cata_mod#424]
This appears to happen with all of the NPC's in the Makeshift Command Center, though it might possibly be happening with other NPC's from Cata++ aswell. Upon being attacked, the NPC's will be marked both as "Friendly" and "Attacking to Kill" at the same time, which leads to them threatening to kill you and pulling out their weapons, only to put their weapons back and just ignore you attacking them, even over extended periods of time.

**Comment by chaosvolt** [comment]
Can you test this with vanilla NPCs like at the refugee center? Sounds like a "DDA being DDA" AI code bug than anything mod-specific to me.

**Comment by Eevim** [comment]
I tested it at the Refugee Center by ramming my ambulance into the front entrance and punching a guard, which aggro'd them and I got hacked and shot to death by the NPC's there.


![refugeecentertest](https://user-images.githubusercontent.com/109960172/184460856-b031f240-0bc9-4659-8f53-0e1ada6a55d7.png)

**Comment by Eevim** [comment]
I tested it at the refugee center by ramming my ambulance into the front entrance and punching a guard, which aggro'd the NPC's and made them start to attack me with both melee weapons and guns and I died. (also sorry for accidentally closing the issue)

![refugeecentertest](https://user-images.githubusercontent.com/109960172/184460927-9225b097-fc67-41f3-bbfa-e36fdac2ecd7.png)

**Comment by chaosvolt** [comment]
Hmm, weird. Not sure what might differ in the NPC JSON that could cause this. :/

**Comment by Eevim** [comment]
If I remember correctly the NPC's in the Makeshift Command Center are automatically friendly towards the player, perhaps the game doesn't get rid of their "Friendly" status when an NPC is attacked or otherwise provoked as it should and accidentally makes it so that they are attacking to kill the player and be friendly towards the player at the same time?

**Comment by chaosvolt** [comment]
Could be it, I'll check faction relations when I get the chance.
