### ISSUE TITLE
Please update the translation

### ISSUE THREAD

**Issue by AquiloSpiritus** [Noctifer-de-Mortem/nocts_cata_mod#429]
I have updated the translation. I can't vouch for the literary quality (machine adaptation), but at least it doesn't contain gross errors.

I don't have access to upload files

https://dropmefiles.com/1g2M2

Created for version BN

**Comment by chaosvolt** [comment]
The way you'd normally update is via making a pull request.

**Comment by AquiloSpiritus** [comment]
I am not a git expert. I tried to make a pr, but I decided that for this I need to create a fork ...

**Comment by AquiloSpiritus** [comment]
It seems that he created a PR. Let me know if I did something wrong...
