### ISSUE TITLE
Eusocial zombie implementation.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Noctifer-de-Mortem/nocts_cata_mod#45]
Have zombies be an evolving threat instead of just annoying when alone and their main danger being numbers. The use of monster evolution is planned to be used to have variants of the same zombie pop up but with small changes like some gaining basic path finding or learning how to track.

Planned in two phases:
1.) Update zombie of this mod
2.) Add variants of vanilla zombies.

Ideas include:
-Have military zombies start unarmed or with slung weapons; then have unarmed have a chance to evolve to a variant that uses a knife and one with slung weapon learned how to use said weapon but poorly.
-Add zombies with evolving path finding based on type (zombie brute will have a worse path finding than a zombie scientist for example).
-Zombie who can use guns or with advance path finding can't revive.
Have "hunter-like" and some military zombies be able to track player instead of always hostile.
-Some zombies learn limited fighting techniques or how to punch better, for lack of a better term...

**Comment by chaosvolt** [comment]
Might be obsoleted, or at least harder to implement, since soldier zombies now have evolutions.

**Comment by Noctifer-de-Mortem** [comment]
Maybe, altho zombie evolutiobs might help. Haven't gotten around this because...reasons...

**Comment by chaosvolt** [comment]
Is fine. Not sure how easy or hard it'll be to alter or add to evolutions though. If they evolve into a monstergroup it'll be easier than if they evolve into specific monsters, I think.
