### ISSUE TITLE
Can't use crank charger of thee Survivor's Crank Rifle 

### ISSUE THREAD

**Issue by WreckingAbandon** [Noctifer-de-Mortem/nocts_cata_mod#452]
It says I should have 1 charge of something while I have 0. Which is precisely why I wanna charge it in the first place but is somehow the one preventing me from doing so.

**Comment by chaosvolt** [comment]
DDA or BN? And does the vanilla hand-crank charger also do this?

**Comment by WreckingAbandon** [comment]
The regular crank charger does fine, although it doesn't accept the capacitence mag so I still can't charge it there, though I only vaguely remember that being possible. I'm in DDA btw, and I can insert the mag into the gun, its just that the crank action can't be performed.

**Comment by chaosvolt** [comment]
Hmm, not sure why it'd start acting up like that, but my rough guess is probably something involving the `ammo_scale` updates. Just tested and indeed it doesn't seem to want to work right, lemme see if there's any easy fix...

**Comment by chaosvolt** [comment]
Ahah, transforming it into a tool that can then be cranked also works.
