### ISSUE TITLE
Monomolecular Sword

### ISSUE THREAD

**Issue by ICEAgent0** [Noctifer-de-Mortem/nocts_cata_mod#456]
Had an issue with the Monomolecular Sword bionic where I was unable to unequip the item. I had deactivated the bionic but that never did anything, and I was stuck using it. It might be because it uses the "NO_UNWIELD" and "NO_DROP" flags instead of "BIONIC_WEAPON"

**Comment by chaosvolt** [comment]
Ah right, guessing it needs updating for the DDA version. Out of curiosity, they ever fix that issue where the hacks to change bionic weapon behavior broke mech weapons?

**Comment by chaosvolt** [comment]
Aight, thanks for pointing it out, do tell if it still acts up afterward.

**Comment by ICEAgent0** [comment]
> Aight, thanks for pointing it out, do tell if it still acts up afterward.

Thanks man, appreciate it. Not sure about the other issue, i'm not super clued up on what they're doing with the updates, sorry
