### ISSUE TITLE
Rebalance Rebuilding Civilisation Books

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Noctifer-de-Mortem/nocts_cata_mod#46]
Make each two books into two tiers:

Tier 1: From 0-6 skill leveling, as boring to read as a technical book, somewhat common and/or found in common places, no recipes.

Tier 2: From 6-10 skill leveling, the most boring type of book you can read, somewhat rare and/or found only in rare book locations (mansions, prepper stashes, ect.), no recipes.

All existing books would be converted to tier 1.

**Comment by chaosvolt** [comment]
Might work. Other observations as posted elsewhere:
* Int cost, morale, and time per chapter are all evidently intended to be the worst available option. Not sure if it's an ideal balancing factor, but it isn't always the case as some books in vanilla are flat-out worse, but balancing to fit means the books cease to be consistent with each other.
* As for rarity, either way I see a few good ways to do so. Puiting them in mansions is most easily done via something like this:
```
  {
    "id": "mansion_bookcase",
    "type": "item_group",
    "subtype": "collection",
    "groups": [
      [ "magic_books", 8 ]
    ]
  },
```
That way not only avoids having to juggle the weights of all other books in `mansion_books` but also precludes them showing up in bookstores or libraries, as they cite `mansion_books` too.
