### ISSUE TITLE
Only Sentinel Power Storage CMB drop when dissecting augmented zombies (DDA)

### ISSUE THREAD

**Issue by MonkWho** [Noctifer-de-Mortem/nocts_cata_mod#486]
I've been away from the game for couple years and when I came back I learned that in vanilla most of CBM zombie harvesting has been removed. Zomborgs and the time traveling faction are the main way forward. But I also noticed that in this mod augmented zombies drop CBMs. Been playing several days and dissected a bunch of augmented zombies from this mod and every time only got Sentinel Power Storage CMBs.

I looked in c_monster_harvest.json and ran some tests trying to get other CBMs to drop. But it has not worked so far and I got frustrated enough that I decided to post here. Do I have a mod conflict that is causing this? Is there something in the base game that is blocking CBM drops from any zombies other than zomborgs? Am I just that unlucky that in couple dozen dissected augmented zombies all they ever dropped were Sentinel CBMs?

Mod list:
[
  "dda",
  "BL9_100monres",
  "secronom",
  "secronom_lore_expansion",
  "bow_opness",
  "Cata++",
  "Dorf_Life",
  "light_weariness",
  "alt_map_key",
  "MMA",
  "MMA_Mods_Extension",
  "more_survivor_notes",
  "more_survivor_stuff",
  "ks_variety_pack",
  "blazemod",
  "Tankmod_Revived",
  "sees_player_retro",
  "MST_Extra",
  "culinary_days_ahead",
  "no_npc_food",
  "no_fungal_growth",
  "Nonperishable_Overhaul",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "translate_dialogue",
  "Tamable_Wildlife"
]

**Comment by chaosvolt** [comment]
```
  {
    "id": "CBM_SOLDAT_ZOMBIE_GENERIC",
    "type": "harvest",
    "entries": [
      {
        "drop": "bio_power_storage_sentinel",
        "type": "bionic",
        "flags": [ "FILTHY", "NO_STERILE", "NO_PACKED" ],
        "faults": [ "fault_bionic_salvaged" ]
      },
      {
        "drop": "bionics_soldat_zombie_generic",
        "type": "bionic_group",
        "flags": [ "FILTHY", "NO_STERILE", "NO_PACKED" ],
        "faults": [ "fault_bionic_salvaged" ]
      },
      { "drop": "meat_tainted", "type": "flesh", "mass_ratio": 0.25 },
      { "drop": "fat_tainted", "type": "flesh", "mass_ratio": 0.08 },
      { "drop": "bone_tainted", "type": "bone", "mass_ratio": 0.1 }
    ]
  },
```

Yep, currently it's only sentinel power storage. Given some issues in the BN version preventing the player from installing multiple power storage items, together with https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/428, this probably will warrants a nerf sometime soon.

**Comment by MonkWho** [comment]
Shouldn't that also trigger "bionics_soldat_zombie_generic" bionic_group and pull from c_item_groups.json list? This harvest section drops a sentinel, fat, meat, and bone but nothing from the bionic_group. As a test I even tried removing everything except that bionic_group but then dissecting returned nothing at all.

**Comment by chaosvolt** [comment]
It should be, yes. o.O

**Comment by MonkWho** [comment]
I fixed the issue with pull mentioned above. I just got lucky in my current playthrough and found a bunker that had an Apophis and a bunch of other stuff so I had an incentive. Had to create all new corpses for fix to work but debug menu is easy enough to use.
