### ISSUE TITLE
Invalid tool quality id for fishing rod O.G Stable

### ISSUE THREAD

**Issue by Spacer-1970** [Noctifer-de-Mortem/nocts_cata_mod#489]
When loading/creating a save with the cata++ mod enabled, it gives 2 errors about the fishing rod having an invalid tool quality id and then the game crashes. This is on the O.G Gaiman stable release

Below are the screenshots of the error taking place plus the crash log:
![Screenshot (466)](https://user-images.githubusercontent.com/92626947/227614343-145d77ac-f05a-4102-8e6c-e37043eb3b4e.png)
![Screenshot (467)](https://user-images.githubusercontent.com/92626947/227614356-dbaf3949-a906-4e6a-a7a0-fe4f37704fb9.png)
![Screenshot (468)](https://user-images.githubusercontent.com/92626947/227614364-524fe2b6-b92f-4763-bfc3-564b2ed1e861.png)
[crash.log](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/files/11065571/crash.log)

**Comment by chaosvolt** [comment]
Ah, looks like https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/480 concerns a change that was merged in DDA after 0.G stable was released, and it made it into said release.

**Comment by chaosvolt** [comment]
Should now be fixed with: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases/tag/0.G-take-2
