### ISSUE TITLE
Multiple errors on startup o.g experimental

### ISSUE THREAD

**Issue by Spacer-1970** [Noctifer-de-Mortem/nocts_cata_mod#490]
When booting up a save with the cata++ mod on the 0.g experimental version, it gets multiple errors.

[debug.log](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/files/11068044/debug.log)

I will include the screenshots and the debug file
![Screenshot (500)](https://user-images.githubusercontent.com/92626947/227697174-44cd5412-5fcb-4378-a631-b5defff97836.png)
![Screenshot (495)](https://user-images.githubusercontent.com/92626947/227697177-6ad48415-21d6-459c-87ed-dae9a0af3bf0.png)
![Screenshot (494)](https://user-images.githubusercontent.com/92626947/227697178-7b281fb9-b7cc-4ebf-a877-ffe8131bd9ab.png)
![Screenshot (483)](https://user-images.githubusercontent.com/92626947/227697181-4b25a06b-2e64-407c-aabf-91ae1fa3f1a7.png)
![Screenshot (482)](https://user-images.githubusercontent.com/92626947/227697182-cc625541-e29b-4db2-92e7-6acbdea283ad.png)
![Screenshot (477)](https://user-images.githubusercontent.com/92626947/227697186
![Screenshot (473)](https://user-images.githubusercontent.com/92626947/227697207-ceb9b4b7-b92e-42f0-8c4e-f4ae55d4aae4.png)
![Screenshot (474)](https://user-images.githubusercontent.com/92626947/227697211-d1716cad-6aca-41b2-a28b-e33afbb7eff5.png)
![Screenshot (475)](https://user-images.githubusercontent.com/92626947/227697214-5e5e05cc-7850-4a49-be62-f377427bc197.png)
![Screenshot (478)](https://user-images.githubusercontent.com/92626947/227697215-03eecbe4-e3d1-4392-b91a-df9fa014b0fc.png)
![Screenshot (479)](https://user-images.githubusercontent.com/92626947/227697217-ae1a4974-9cf8-414d-9938-6a086155781e.png)
![Screenshot (480)](https://user-images.githubusercontent.com/92626947/227697223-e98839a2-c083-4600-8de5-7249657c2b3e.png)
![Screenshot (481)](https://user-images.githubusercontent.com/92626947/227697225-e6cc85bf-596e-4119-aa5b-6415633e2e11.png)
![Screenshot (484)](https://user-images.githubusercontent.com/92626947/227697229-e1ec8b13-9f2b-44a4-9229-4f89eb31c0ca.png)
![Screenshot (485)](https://user-images.githubusercontent.com/92626947/227697234-5605472d-d8a8-4690-851d-597a7715b140.png)
![Screenshot (486)](https://user-images.githubusercontent.com/92626947/227697237-082e4659-c8e2-4ef9-8657-6460a089bfb2.png)
![Screenshot (487)](https://user-images.githubusercontent.com/92626947/227697239-3f234f7f-feff-4004-95cc-1b53df67c140.png)
![Screenshot (490)](https://user-images.githubusercontent.com/92626947/227697242-9cd3c66c-7183-4e78-8e6e-d321ab2ffe6f.png)
![Screenshot (491)](https://user-images.githubusercontent.com/92626947/227697243-a760bee9-b01e-483e-9d5d-9aad6256e198.png)
![Screenshot (492)](https://user-images.githubusercontent.com/92626947/227697247-12b386da-3844-4496-b516-a70d01a22afb.png)
![Screenshot (493)](https://user-images.githubus
![Screenshot (496)](https://user-images.githubusercontent.com/92626947/227697262-a0178582-9ba0-46e3-85d2-ff6817232c24.png)
![Screenshot (497)](https://user-images.githubusercontent.com/92626947/227697268-5c5d83f5-4b35-43ca-a428-383366dbe290.png)
![Screenshot (498)](https://user-images.githubusercontent.com/92626947/227697271-f4233854-79f4-47e8-bc35-c82921a311a4.png)
![Screenshot (499)](https://user-images.githubusercontent.com/92626947/227697274-3f20f457-286f-412e-b4fc-2540e5cfa21d.png)
![Screenshot (502)](https://user-images.githubusercontent.com/92626947/227697277-b34cc132-a3f1-4a80-9c6b-47b8c158a5a1.png)
![Screenshot (503)](https://user-images.githubusercontent.com/92626947/227697278-3ebf92e3-68ac-410c-92c6-d074f0ba62e8.png)
![Screenshot (504)](https://user-images.githubusercontent.com/92626947/227697281-ac6cbba0-7a46-4c0b-bbcf-dc2c10661455.png)
![Screenshot (505)](https://user-images.githubusercontent.com/92626947/227697283-2d83db2f-d582-4a47-8bbc-4ae6dd06f86c.png)
![Screenshot (476)](https://user-images.githubusercontent.com/92626947/227697286-ebad2fa5-70b9-407d-90ef-893f3cc1f906.png)
![Screenshot (501)](https://user-images.githubusercontent.com/92626947/227697288-d07eedb1-7d99-4314-96ea-c044c283b55c.png)
-0cc37057-f9a3-49a4-9aa7-1e0fbd79af8c.png)
![Screenshot (506)](https://user-images.githubusercontent.com/92626947/227697188-db815611-26a6-43a7-85da-06a181570f15.png)
![Screenshot (509)](https://user-images.githubusercontent.com/92626947/227697192-1ac7c8d3-a2de-4574-89f2-dc94872776e1.png)
![Screenshot (508)](https://user-images.githubusercontent.com/92626947/227697194-5135076b-9e6e-4a5f-a04a-cc65c772c43b.png)
![Screenshot (507)](https://user-images.githubusercontent.com/92626947/227697197-d07eac29-d228-4c9b-a8b8-26af676ae14e.png)
![Screenshot (488)](https://user-images.githubusercontent.com/92626947/227697201-41a651b0-0c0e-40c7-93cd-1f5128e993e5.png)
![Screenshot (489)](https://user-images.githubusercontent.com/92626947/227697205-064e42ca-ed11-42da-b046-0c385c773a5e.png)
![Screenshot (472)](https://user-images.githubusercontent.com/92626947/227697206-e6b8b6f1-0e64-4fe8-952d-df786dde58a7.png)

**Comment by chaosvolt** [comment]
I do see you're using the 0.G Stable release in 0.G experimental, but most of that seems to involve stuff they've decided to delete after the stable release. Will have to look at it tomorrow.
