### ISSUE TITLE
using the hm12 on a laser turret crashes the game

### ISSUE THREAD

**Issue by Jazztree013** [Noctifer-de-Mortem/nocts_cata_mod#498]
using the hm12 base game rifle on a laser turret located at the unkown bunker makes the game crash.

**Comment by chaosvolt** [comment]
Hmm, looking into it now. Does this happen with any of the regular turrets?

**Comment by chaosvolt** [comment]
Tested this first in a build from april 8th and couldn't reproduce it, grabbed the most recent build (`2023-04-11-1808`) and it worked just fine, even when the stun triggered.
