### ISSUE TITLE
Controlled Monster AI tag on player after injecting nano-mutagenic serum

### ISSUE THREAD

**Issue by Phenomphear** [Noctifer-de-Mortem/nocts_cata_mod#500]
Injected self with nano-mutagenic serum and received Controlled Monster under effects and 2 mutations.
![image](https://user-images.githubusercontent.com/28910998/231874487-ffd42b70-6bc9-4a6e-9628-881c47e14916.png)

**Comment by chaosvolt** [comment]
Was found out later on to most likely be Secronom.
