### ISSUE TITLE
DDA version still getting errors, seems like some of the proper jsons are in BN?

### ISSUE THREAD

**Issue by WreckingAbandon** [Noctifer-de-Mortem/nocts_cata_mod#508]
I keep getting errors about the superalloy composite not having the bash_resist mandatory member, seems the c_materials.json of BN is the proper one for some reason. I get errors about things in legacy.json too about misplaced "melee_damage" being an invalid or misplaced field name.

**Comment by WreckingAbandon** [comment]
Putting the materials.json in BN's Surv_help folder into DDA's seems to do the trick, doing it with the legacy.json does not help tho.

**Comment by chaosvolt** [comment]
You're using the wrong version. What version of DDA are you using, and what version of Cata++? If you're using current experimental DDA, use the `nocts_cata_mod_DDA` folder, NOT the `nocts_cata_mod_BN` folder. Make sure you're deleting the old folder beforehand, not simply dumping the new version directly on top of the old one.

**Comment by chaosvolt** [comment]
Yeah no, just tested current master branch of Cata++ in most recent build (2023-04-26-0511), no load errors. Update your mod version.
