### ISSUE TITLE
Error with the latest experimental

### ISSUE THREAD

**Issue by Proxima-b** [Noctifer-de-Mortem/nocts_cata_mod#512]
DEBUG    : bionic bio_power_armor_interface_mkII for profession bio_weapon_b does not exist

 FUNCTION : void profession::check_definition() const
 FILE     : src/profession.cpp
 LINE     : 357
 VERSION  : 3010c62

**Comment by chaosvolt** [comment]
Looks like another case of "DDA removes yet another fun thing for realism" via https://github.com/CleverRaven/Cataclysm-DDA/pull/65077
