### ISSUE TITLE
New error message showing up

### ISSUE THREAD

**Issue by Proxima-b** [Noctifer-de-Mortem/nocts_cata_mod#514]
DEBUG    : itype 'legrig_surv' uses undefined flag 'NO_QUICKDRAW'. Please add corresponding 'json_flag' entry to json.

 FUNCTION : Item_factory::finalize_post(itype&)::<lambda(const flag_id&)>
 FILE     : src/item_factory.cpp
 LINE     : 690
 VERSION  : 39e7de0

**Comment by chaosvolt** [comment]
Aight, will work on it in a bit now that I'm home.
