### ISSUE TITLE
2 rebuilding civilization book errors

### ISSUE THREAD

**Issue by Phenomphear** [Noctifer-de-Mortem/nocts_cata_mod#53]
` DEBUG    : warnings for type encyclopedia_gun_advance:
uses invalid book skill.

 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1093`

and

`DEBUG    : warnings for type encyclopedia_electronics_advance:
uses invalid book skill.

 
 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1093`

**Fix below:**
"id": "encyclopedia_gun_advance",

line 769 "skill": "marksmanship", needs to read "skill": "gun" instead

-----------------------

"id": "encyclopedia_electronics_advance", electronics is spelt wrong for skill used.

"skill": "eletronics" needs to read "skill": "electronics"

Great mod guys 👍

**Comment by chaosvolt** [comment]
Got it. :3
