### ISSUE TITLE
charges defined but can not have any

### ISSUE THREAD

**Issue by waveyl** [Noctifer-de-Mortem/nocts_cata_mod#545]
gas_slime_scrap(cata++)
caveyot_bush_quarry_cooked(Dorf_Life)
potted_meat(Nonperishable_Overhaul)

Caused by DDA#60885

**Comment by chaosvolt** [comment]
Whoops, will update these in a bit.

**Comment by chaosvolt** [comment]
Updated Nonperishable Overhaul and Dorf Life, Cata++ update to follow in a sec.
