### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by MintyUwU** [Noctifer-de-Mortem/nocts_cata_mod#613]
i think

**Comment by chaosvolt** [comment]
You'll need to be more specific. What's the actual problem? DDA or BN version?

**Comment by MintyUwU** [comment]
Sorry, I didn't mean to sound rude.
I have latest Experimental DDA, and downloaded master of Cataclysm++ then extracted the right files, but there were error messages and it just wouldnt load
maybe it's because experimental builds change so rapidly?

**Comment by chaosvolt** [comment]
Probably, I'd have to see what errors they are and try to figure out what JSON changes we missed.

**Comment by chaosvolt** [comment]
Tested current master on build `2024-04-28-1820`, no load errors at first:
![image](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/assets/11582235/9b8cc579-1808-496c-b30d-5ef9e460789f)
Starting in the lab however:
![image](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/assets/11582235/90b003cb-5ef3-43c0-8841-44103a32c978)

I then decided to do an evac shelter start without Cata++ and hmm, no errors. I'm not sure what that means though...

**Comment by chaosvolt** [comment]
Okay I tried it again in the same build and it works fine.
![image](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/assets/11582235/3a108d03-099b-4047-b1fc-7e53e8869b93)

My guess is this is a code thing of some sort happening at random. I'd say see if you can get it happening in a vanilla world too, and if so go tell them about it.

**Comment by MintyUwU** [comment]
i used one of forks of cataclysm++ and it works somehow

**Comment by chaosvolt** [comment]
Yeah uh, far as I can tell this is a code thing on DDA's end that triggers at random, unless there's some way to narrow down whether a specific itemgroup or other random element is causing it and whether it's actually specific to Cata++.

Go open an issue reporting that those messages print at random with no discernible cause, paste what messages are printing, and point out how unusable they are for actually finding out what is erroring.
