### ISSUE TITLE
 There are too many mandatory overmap specials (356 > 144). Some of them may not be placed.

### ISSUE THREAD

**Issue by waveyl** [Noctifer-de-Mortem/nocts_cata_mod#623]

**Comment by chaosvolt** [comment]
Got a PR link to what might've screwed this up? Last I checked, Arcana and Cata++ use unique specials with below 100% spawn rate, which are supposed to not count against the special limit.

Actually uh, what the fuck? **_356 specials?_** Arcana only has a total of FIVE specials places at game start, something is absolutely wrong as hell with DDA and it's not either of the mods, double-check this in vanilla.

**Comment by chaosvolt** [comment]
Oh wait, I see the cause. https://github.com/CleverRaven/Cataclysm-DDA/pull/74290 changed the flag around so all overmap specials with just `UNIQUE` are now mandating giant amounts of specials.
