### ISSUE TITLE
Reading speed multiplier enchantment broken

### ISSUE THREAD

**Issue by PGR-14** [Noctifer-de-Mortem/nocts_cata_mod#635]
DEBUG    : Error: Invalid enum string 'READING_SPEED_MULTIPLIER' for 'enchant_vals::mod'

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 987
 VERSION  : 47cb4c4

**Comment by chaosvolt** [comment]
What version of the mod and of Cata are you using? Sounds like you're using current DDA version of the mod with a stable build of DDA, or with BN.

See DDA's use of that enchantment for reference: https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/mutations/mutations.json#L853

**Comment by PGR-14** [comment]
cdda-windows-tiles-sounds-x64-2024-07-05-0342
When the Velvet worm audit was merged (DDA), w/ the latest version of the mod

**Comment by PGR-14** [comment]
I didn't realize, sorry for the inconvenience.
