### ISSUE TITLE
DDA: See cost uses invalid number format

### ISSUE THREAD

**Issue by Shad0wBlad321** [Noctifer-de-Mortem/nocts_cata_mod#639]
DEBUG    : Error: Json error: data/mods/nocts_cata_mod_DDA/legacy.json:1202:5: <color_white><color_cyan>In b_field: See cost uses invalid number format</color>

    "result": "surcanuncraft",
    "obsolete": true
<color_light_red>  },</color>
   <color_cyan>▲▲▲</color>
  {
    "id": "b_field",
</color>

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 1013
 VERSION  : cdda-experimental-2024-08-07-0555 293f801

**Comment by chaosvolt** [comment]
Fixed by https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/640
