### ISSUE TITLE
<color_white><color_cyan>In Survivor_Holdout_1: See cost uses invalid number forma

### ISSUE THREAD

**Issue by paulogabbi** [Noctifer-de-Mortem/nocts_cata_mod#645]
DEBUG    : Error: Json error: C:/Users/paulogabbi/Downloads/dda/userdata/mods/nocts_cata_mod_DDA/Terrain/overmap_terrain.json:1:2: <color_white><color_cyan>In Survivor_Holdout_1: See cost uses invalid number format</color>

<color_light_red>[</color>
<color_cyan>▲▲▲</color>
  {
    "id": "Survivor_Holdout_1",
</color>

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1064
 VERSION  : 3484533

**Comment by chaosvolt** [comment]
Are you using current master branch of the mod, or a stable release?

**Comment by paulogabbi** [comment]
master branch

**Comment by chaosvolt** [comment]
And using recent experimental builds of DDA? My guess from the looks of it is you're using newer version of the mod with old version of DDA.

**Comment by paulogabbi** [comment]
weird thing is i am using both of the latest updates, the mod and the experimental DDA

**Comment by paulogabbi** [comment]
welp tried redownloading CDDA and everything else but now i am getting alot more errors wtf

**Comment by chaosvolt** [comment]
Hmm. Make sure you're actually correctly matching the right version of the mod with latest experimental DDA, I'm grabbing latest release to test in a sec.

**Comment by chaosvolt** [comment]
And what I'm getting are...looks like errors caused by https://github.com/CleverRaven/Cataclysm-DDA/pull/75865 having removed most of the plutonium batteries outright, which bricks the Omnitech ones because they inherited from those.

**Comment by paulogabbi** [comment]
yeah over here i cannot even create a character using cata++ sadly  it gives a error

**Comment by chaosvolt** [comment]
Should now be fixed, load-tested.

**Comment by paulogabbi** [comment]
oh yeah it works now Thank you for the help

**Comment by chaosvolt** [comment]
I'm gonna have to check my mods too just in case, I suspect...
