### ISSUE TITLE
PR #5635 breaks prevents games running this mod from loading.

### ISSUE THREAD

**Issue by Proxiehunter** [Noctifer-de-Mortem/nocts_cata_mod#659]
At least I assume from [RoyalFox2140](https://github.com/RoyalFox2140)'s additional context in [this PR](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5635) that this remains the cause. Not sure how I can tell which mod is causing an error but I know that was pointed out in the thread as preventing games from loading. 

![image](https://github.com/user-attachments/assets/3b9e8cda-c96a-45ce-86cb-8c38a7d3b322)

**Comment by chaosvolt** [comment]
You're using an outdated version of the mod, it was updated when https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/658 was merged.

**Comment by Proxiehunter** [comment]
Was just coming back to update once I realized I'd _downloaded_ the updated version but failed to _install_ it. Sorry about that.

**Comment by chaosvolt** [comment]
Always a modpack issue isn't it... ._.
