### ISSUE TITLE
Add dc freezer?

### ISSUE THREAD

**Issue by adamkad1** [Noctifer-de-Mortem/nocts_cata_mod#74]
A large fridge is cool but it doesnt keep stuff as well as a minifreezer, so maybe add a big freezer? Though theres no freezer furnis yet so maybe you could just make it 4-5 minifreezers and a dc fridge for simple space savings

**Comment by chaosvolt** [comment]
:eyes:

Little late on that, the DC fridge was just removed due to:
1. The `e`xamine prompt being more hassle than it's worth.
2. This PR making the feature available via in-repo mod: https://github.com/CleverRaven/Cataclysm-DDA/pull/28386

**Comment by adamkad1** [comment]
well thats fine i guess

**Comment by adamkad1** [comment]
also apparently the changes to fridge made it not drop a refridgerant tank
