### ISSUE TITLE
supersoldier zombies have ups conversion mods and not ups

### ISSUE THREAD

**Issue by adamkad1** [Noctifer-de-Mortem/nocts_cata_mod#75]
they are supposed to have ups not a conversion mod right?

**Comment by adamkad1** [comment]
bump?

**Comment by chaosvolt** [comment]
Whoops. Oughta pester Noct to look at this. Does seem to be an oddity yeah, the drops likely should consistently favor either a chance of a UPS or a UPS bionic, and be consistent between player and monster versions (possible with NPC versions too, with have an advanced UPS out of nessecity).

**Comment by chaosvolt** [comment]
So, it seems to me like giving them the UPS bionic would be a reasonable choice, as this is less efficient than an advanced UPS but more sustainable in the long term, and half the super soldier profressions start with one to begin with. So this'll be a simple

The NPCs meanwhile have to stick with using an advanced UPS out of necessity, as giving them bionics doesn't quite seem to work right, plus getting NPCs to use laser weapons at all is like herding cats.
