### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lool228** [Noctifer-de-Mortem/nocts_cata_mod#87]
DEBUG    : Error: data/mods//Cataclysm_Plus_Plus/Npc/TALK_MSCI.json: line 72:7: dynamic line not supported

 Apophis...  It was a Bio-Weapon specifically designed to eliminate every other Bio-Weapon and Bio-Weapon scientist.  Now we can try to get things fixed up eventually, and work on research that might benefit others out there."
      }
    },
      ^
    "responses": [
10      { "text": "Oh, good luck, I suppose.", "topic": "TALK_MSCI" },
10      {
10
 
 FUNCTION : bool main_menu::load_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 965

**Comment by Kibawan** [comment]
Same thing for me. I download the Mod Manualy 3 times, one with the launcher

**Comment by chaosvolt** [comment]
Will have a fix up in a bit, cause is changes to syntax in https://github.com/CleverRaven/Cataclysm-DDA/pull/29045
