### ISSUE TITLE
Cata++ Bonkered on more recent patches!

### ISSUE THREAD

**Issue by Helldrone** [Noctifer-de-Mortem/nocts_cata_mod#94]
Hello, i experienced a problem with the cata++
I updated from
![image](https://user-images.githubusercontent.com/49344129/56383948-70f11e80-621b-11e9-8d17-4034581bf1b0.png)
to
![image](https://user-images.githubusercontent.com/49344129/56383958-75b5d280-621b-11e9-9292-fd13d8fdc2d9.png)
And i got this
![image](https://user-images.githubusercontent.com/49344129/56383966-7a7a8680-621b-11e9-9223-624b62b4c60a.png)

I don't know how to fix it.
Just to give information i'm running Win10 and here's the mod list

![image](https://user-images.githubusercontent.com/49344129/56384005-92eaa100-621b-11e9-8ace-3062a339ce1f.png)

**Comment by hexob** [comment]
happens to me too

**Comment by scanevaro** [comment]
same

**Comment by chaosvolt** [comment]
Gah, likely cause is changes to mission syntax. Will have a fix up shortly if Noct doesn't get to it.
