### ISSUE TITLE
[8932] Cata++ Bonkered once more!

### ISSUE THREAD

**Issue by Helldrone** [Noctifer-de-Mortem/nocts_cata_mod#98]
Hello once more! i'd like to report an issue, seeing how the recent patches funked the mod once more.
Old build: 
![image](https://user-images.githubusercontent.com/49344129/57538112-ff9f1a00-7347-11e9-8f2f-5bc63f88959f.png)
To 
![image](https://user-images.githubusercontent.com/49344129/57538142-0e85cc80-7348-11e9-8001-9d9442cd7134.png)

None of the two Cata++ mods functions with the latest build for me atleast.
![image](https://user-images.githubusercontent.com/49344129/57538203-307f4f00-7348-11e9-9a2b-716cddbc75f4.png)

This is what i get.

![image](https://user-images.githubusercontent.com/49344129/57538276-5c9ad000-7348-11e9-9f99-d3ef794a244e.png)

My mods haven't changed since last time.
![image](https://user-images.githubusercontent.com/49344129/57538302-6ae8ec00-7348-11e9-853d-2d1495c2091d.png)

Thank you for you time!

**Comment by chaosvolt** [comment]
Er...are you sure you're using the newest version of the master branch of this mod? Update manually (without using the launcher), retest, then tell me if it persists. Just in case I'll test it as well.

**Comment by chaosvolt** [comment]
I'm testing this and getting an entirely different error related to martial arts.

**Comment by chaosvolt** [comment]
I just chucked out a fix for the error I encountered, since Noct's likely busy and it was easily done.

Still not getting the error you reported, as that's from a dialogue change that's a couple weeks old. My advice:
1. Update manually: https://github.com/Noctifer-de-Mortem/nocts_cata_mod
2. Don't use the launcher.
3. Make sure you deleted the old version of the mod from your data/mods folder.
4. Don't use the launcher.

**Comment by Helldrone** [comment]
I have updated it manually as cata++ is the mod i've dealt with the most so far, i also went between the two [0.D Stable] cata++ version, this is what i get with the regular one.

![image](https://user-images.githubusercontent.com/49344129/57542345-b5229b00-7351-11e9-8a0b-8fe4b1af1f76.png)

I thought i had to change

**Comment by chaosvolt** [comment]
I literally just merged the fix for that.

**Comment by Helldrone** [comment]
But it works! Calm thoughts!

**Comment by chaosvolt** [comment]
Yay. Hopefully nothing else will come up for a while, been meaning to tackle some ideas to show Noct but been wrapped up in a lot of other stuff.

**Comment by Helldrone** [comment]
i Just appreciate your immense short notice, saved my weekend.

**Comment by chaosvolt** [comment]
No worries, only just good luck that I was on not long after you opened the issue, if I'd already been out and about it would've taken a while for me to be around to check, and unsure if Noct would be on to check beforehand.
